### ISSUE TITLE
Improve handling of error 412

### ISSUE THREAD

**Issue by gturri** [Zero-Waste-Paris/slack-agenda-app#130]
Though our Slack has a rather low trafic, we had a couple of those errors lately: when a user tries registering on an event, it fails because the caldav server replies with a 412 error.

Though this error may probably not be avoided all the time, we probably have something to fix, because we've observed it twice in only a few days.

Here is an example of log we had:

```
SlackApp.DEBUG: HMAC check OK. [] []                                                                                                                                  
SlackApp.DEBUG: register from channel mail xxx@gmail.com xxx xxx [] []                                                                                 
MySQLAgenda.INFO: updating 0ba98fe0-07be-44ad-83cf-0ea1197f1857.ics [] []                                                                                             
CalDAVClient.DEBUG: will update 0ba98fe0-07be-44ad-83cf-0ea1197f1857.ics with ETag 63787166625 [] []                                                                  
CalDAVClient.ERROR: Bad HTTP response code: 412 for https://www.google.com/calendar/dav/agenda@zerowasteparis.fr/events/0ba98fe0-07be-44ad-83cf-0ea1197f1857.ics [] []
CalDAVClient.ERROR: in (updateEvent). [] []                                                                                                                           
CalDAVClient.ERROR: HTTP/2 412  content-length: 65 content-type: text/xml; charset=UTF-8 expires: Mon, 01 Jan 1990 00:00:00 GMT cache-control: no-cache, no-store, max [...]
```

**Comment by gturri** [comment]
It seems we have at least those issues:

- if a user tries registering to an event via a button on a `/remindEvent` message, and if the registration fails, then the user won't see an error. That's because in this case the request runs `SlackEvents::more_inchannel` which calls `Agenda::updateAttendee` but which then ignores the returned value (stored in the local variable `$response` but never used). Ideally we should handle the case where this returned value is `false` since it indicates that we failed to update the event on the caldav server. (an example where this is correctly handled is in `SlackEvent::register`). The issue is that the user doesn't know that his or her registration failed (and is hence not even encouraged to retry)
- we should also probably have some lock on `Agenda::updateAttendee` in order to avoid trying to update the same event concurrently, otherwise we will unavoidably have a 412 error (however this issue may not be so urgent since we currently have a very low trafic so the risk of this issue is likely very low)
- however we also have another issue since the 412 experienced today occured in a non concurrent context (according to the log). I don't know yet how it could occur

**Comment by vhouchouas** [comment]
Maybe the concurrent access is from another client (i.e. thunderbird). 
However I tried to reproduce the error that way... unsuccessfully.

**Comment by gturri** [comment]
You are correct, and I indeed managed to reproduce a similar issue that way (1. post the event with  `/remindEvent`, 2. click `Inscription / plus d'information`, 3. change the event with thunderbird (eg: adding a label), 4. Trying to register).

I guess it means that even if we add lock we should still be able to handle nicely this error. For instance if there is such failure we could attempt once to reload the event and to add the user again. Perhaps also instead of updating the view before the registration is recorded, we could display a message like "registration on-going", so the user isn't mislead?

**Comment by vhouchouas** [comment]
Maybe we can call `checkAgenda` at the begining of `updateAttendee` to be sure that the local agenda is up to date.
Indeed, we can change the message by "registration on-going".

**Comment by gturri** [comment]
Yes, either we could call `checkAgenda` everytime, or just when we attempt one retry after a 412.
IIUC calling it everytime could add (in our setup) ~0.1s of latency on every registration, but it woud be easier to develop.
