### ISSUE TITLE
Handle the case where a user register on a deleted event

### ISSUE THREAD

**Issue by gturri** [Zero-Waste-Paris/slack-agenda-app#134]
The current code would fail with an error on line 696 of agenda.php :

            $ETag = $this->getEvent($vCalendarFilename)[1];

with error `Exception: Trying to access array offset on value of type null`

Steps to reproduce:
1. Create a test event
2. post it in a channel with the command `/remindEvent`
3. open the details of this event
4. delete the event on the caldav server
5. try to register to the event

**Comment by vhouchouas** [comment]
Fixed with #145
