### ISSUE TITLE
Use a sql database as a local cache

### ISSUE THREAD

**Issue by gturri** [Zero-Waste-Paris/slack-agenda-app#33]
Rationale:
- it should be better for performances
- it should make it a bit simpler to handle locks (because the db should handle some of it)

Nb: it should still be possible let users who prefer it to use the filesystem to do so as long as we propose sqlite as a possible backend

Nb2: obviously it would be nice to measure the latency with the current file system cache and the db one, to ensure it improves performances

**Comment by vhouchouas** [comment]
Implemented by pull request #46.
