### ISSUE TITLE
Avoid concurrent updates of the agenda

### ISSUE THREAD

**Issue by gturri** [Zero-Waste-Paris/slack-agenda-app#4]
If two queries arrive at almost the same time at a moment when the agenda needs to be updated, it's possible that both ends up performing this update. That would be the case for instance in this scenario:

- Query 1 reads the contents of ./data/ctag and then enters `geteetags`
- then  Query 2 reads the content of ./data/ctags and then enters `getetags`
- then both will run `updateInternalState`

A way to avoid this would be to have an algo with a lock like this in the `update` method
- read remote ctag
- read local ctag
- if remote_ctag != local_ctag:
  - create an exclusive lock
  - read local ctag (this double check ensure we won't have any concurrent run at all and at the same time avoid locking most of the time. See https://en.wikipedia.org/wiki/Double-checked_locking )
  - if remote_ctag != local_ctag then perform the update (ie: call `getetags`, then `updateInternalState`, then update the local etags file)
  - delete the lock

**Comment by vhouchouas** [comment]
I think this issue is no more relevant since we are using DB from now.

**Comment by gturri** [comment]
yep
