### ISSUE TITLE
implement some log rotate feature

### ISSUE THREAD

**Issue by gturri** [Zero-Waste-Paris/slack-agenda-app#65]
It's not important for now but it may become useful when we have a lot of users, to avoid ending up with tons of old logs.
It seems it could use something like this for instance: https://github.com/cesargb/php-log-rotation

**Comment by vhouchouas** [comment]
What about: https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/RotatingFileHandler.php ?
We just have to change: `new StreamHandler('app.log', Logger::ERROR);` (utils.php L9) into something like
`new RotatingFileHandler('app.log', 10, Logger::ERROR);` (10 days of history).

**Comment by gturri** [comment]
ah, it's cool if it's so simple (and if we don't have to add a new package)! 👍

**Comment by gturri** [comment]
fixed by #76
