### ISSUE TITLE
Fix encoding issue

### ISSUE THREAD

**Issue by gturri** [Zero-Waste-Paris/slack-agenda-app#67]
emoji in event descriptions aren't rendered correctly in slack
![image](https://user-images.githubusercontent.com/308601/146762365-46f8b786-4fd1-440b-b139-df60e26353f1.png)

**Comment by gturri** [comment]
The issue seems to be at the moment where we register the event in the db: 
![image](https://user-images.githubusercontent.com/308601/146769346-8e21734d-cc68-4849-b3eb-b31b8f692a62.png)

**Comment by gturri** [comment]
FTR: turning the PDO connection string to `mysql:host=$this->host;dbname=$this->db_name;charset=utf8mb4`, or even ``mysql:host=$this->host;dbname=$this->db_name;charset=utf8`` (with the charset added at the end) doesn't fix the issue

**Comment by vhouchouas** [comment]
I have the same content when accessing the calendar on https://calendar.google.com/, and on thunderbird. 
Not sure this issue is related to this app.

**Comment by gturri** [comment]
Thanks for this info. Even if it's not related to our app directly, it could be cool if our able is able to handle such event (in the sense that: my firefox was able to correctly display it).
It we manage to reproduce this issue in the future we might want to give this a try: when the caldav client receive a response it could check with https://www.php.net/manual/en/function.mb-detect-encoding.php if it received some utf8 and and if not then convert it with https://www.php.net/manual/en/function.utf8-encode.php

Anyway I guess I'll close this for now
